version: '3.8'

services:

  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: market
    ports:
      - "3307:3306"
    healthcheck: 
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-padmin"]
      interval: 5s
      timeout: 5s
      retries: 10
    volumes:
      - db_data:/var/lib/mysql
      - ./initdb:/docker-entrypoint-initdb.d
    

  # Контейнер приложения
  web:
    build: .
    container_name: my-market
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DB_URL=jdbc:mysql://db:3306/market
      - DB_USER=root
      - DB_PASSWORD=admin

volumes:
  db_data:

